version: '3'

volumes:
  url-protection-checker-data:
    driver: local

services:
  database:
    image: "postgres:11"
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=url-protection-checker
    ports:
      - 5432:5432
    volumes:
      - url-protection-checker-data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=0
      - PORT=8000
      - DATABASE_CREDENTIALS={"password":"postgres","dbname":"url-protection-checker","engine":"postgres","port":5432,"host":"database","username":"postgres"}
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - database
    command: python3 /app/manage.py runserver 0.0.0.0:8000
