# Generated by Django 2.2.24 on 2021-09-27 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='NonPaasSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=90)),
                ('site_url', models.URLField(blank=True)),
                ('is_protected', models.BooleanField(default=False)),
                ('reporting_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=90)),
                ('org_guid', models.CharField(max_length=90)),
                ('check_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=90)),
                ('space_guid', models.CharField(max_length=90, unique=True)),
                ('check_enabled', models.BooleanField(default=True)),
                ('filter_guid', models.CharField(default='-1', max_length=90)),
                ('orgs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.Orgs')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_route', models.URLField(blank=True)),
                ('route_guid', models.CharField(blank=True, max_length=90)),
                ('is_behind_vpn', models.BooleanField(default=False)),
                ('is_behind_sso', models.BooleanField(default=False)),
                ('is_behind_app_auth', models.BooleanField(default=False)),
                ('is_protected', models.BooleanField(default=False)),
                ('reporting_enabled', models.BooleanField(default=True)),
                ('reporting_disabled_reason', models.CharField(blank=True, max_length=120)),
                ('applications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.Applications')),
            ],
        ),
        migrations.AddField(
            model_name='applications',
            name='spaces',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.Spaces'),
        ),
    ]
