# Generated by Django 2.2.5 on 2019-09-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=60)),
                ('primary_app_route', models.URLField(blank=True)),
                ('secondary_app_route', models.URLField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=60)),
                ('space_guid', models.CharField(max_length=60)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
