# Generated by Django 2.2.5 on 2019-09-28 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='is_behind_sso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applications',
            name='is_behind_vpn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applications',
            name='space',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='checker.Spaces'),
            preserve_default=False,
        ),
    ]
