# Generated by Django 2.2.5 on 2019-09-28 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_auto_20190928_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='is_behind_sso',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='is_behind_vpn',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='primary_app_route',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='secondary_app_route',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='space',
        ),
        migrations.CreateModel(
            name='ApplicationsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_route', models.URLField(blank=True)),
                ('is_behind_vpn', models.BooleanField(default=False)),
                ('is_behind_sso', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.Applications')),
                ('spaces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.Spaces')),
            ],
        ),
    ]
