# Generated by Django 2.2.5 on 2019-09-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0003_auto_20190928_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationsitem',
            old_name='application',
            new_name='applications',
        ),
    ]
