# Generated by Django 2.2.5 on 2019-10-04 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0007_auto_20190928_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationsitem',
            name='spaces',
        ),
        migrations.AddField(
            model_name='applications',
            name='spaces',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='checker.Spaces'),
            preserve_default=False,
        ),
    ]
