# Generated by Django 2.2.5 on 2019-11-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0009_auto_20191110_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsitem',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
    ]
