# Generated by Django 2.2.5 on 2019-11-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0010_applicationsitem_is_protected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationsitem',
            old_name='check_enabled',
            new_name='reporting_enabled',
        ),
    ]
