# Generated by Django 2.2.5 on 2019-11-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0012_applicationsitem_is_behind_app_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=90)),
                ('org_guid', models.CharField(max_length=90)),
                ('check_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
