# Generated by Django 2.2.5 on 2019-11-22 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0013_orgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaces',
            name='orgs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='checker.Orgs'),
            preserve_default=False,
        ),
    ]
