# Generated by Django 2.2.5 on 2019-11-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0014_spaces_orgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonPaasSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=90)),
                ('site_url', models.URLField(blank=True)),
                ('is_protected', models.BooleanField(default=False)),
                ('reporting_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
