# Generated by Django 3.0.3 on 2020-03-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0015_nonpaassites'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsitem',
            name='reporting_disabled_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
