# Generated by Django 3.1.4 on 2021-03-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0016_applicationsitem_reporting_disabled_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaces',
            name='cdn_filter_guid',
            field=models.CharField(default='-1', max_length=90),
        ),
        migrations.AddField(
            model_name='spaces',
            name='filter_guid',
            field=models.CharField(default='-1', max_length=90),
        ),
    ]
