# Generated by Django 3.1.4 on 2021-03-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0018_auto_20210315_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaces',
            name='cdn_filter_guid',
        ),
    ]
