# Generated by Django 3.1.4 on 2021-03-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0019_remove_spaces_cdn_filter_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsitem',
            name='route_guid',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
